modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="noplayerlist"
version="1.0.2"
displayName="No Player List"
displayURL=""
updateJSONURL=""
credits=""
authors="Smileycorp"
description="Removes the player list from tab."
